console.log("Hi am new to visual studio");
var fname="saikrishna"; 
console.log(fname);
var lname="goud";
console.log(lname);
var fullname=fname.concat(lname);
console.log(fullname);
var number1=1;
console.log(number1);
var number2=2;
console.log(number2);
console.log(number1+number2);
console.log(number1*number2);
console.log(number1/number2);
console.log(number1-number2);
var bignumber=5.1234;
console.log(bignumber.toFixed(3));
var newname=fullname.replace("saikrishna","sai");
console.log(newname);
console.log(fullname.toUpperCase());
console.log(fullname.toLowerCase());